# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-input=false'
    backendServiceArm: 'Azure for Students(6d897306-d565-4948-bbff-e83dfa654aca)'
    backendAzureRmResourceGroupName: 'tfstate'
    backendAzureRmStorageAccountName: 'tfstate13763'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan -input=false'
    environmentServiceNameAzureRM: 'Azure for Students(6d897306-d565-4948-bbff-e83dfa654aca)'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-input=false tfplan'
    environmentServiceNameAzureRM: 'Azure for Students(6d897306-d565-4948-bbff-e83dfa654aca)'